# Generated by Django 3.0.4 on 2020-03-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('searched_game', models.CharField(max_length=128)),
                ('game_name', models.CharField(max_length=128)),
                ('best_price', models.CharField(max_length=10)),
                ('current_price', models.CharField(max_length=10)),
            ],
        ),
    ]
