# Generated by Django 3.0.4 on 2020-05-03 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('searched_game', models.CharField(max_length=128)),
                ('game_name', models.CharField(max_length=128)),
                ('best_price', models.CharField(max_length=25)),
                ('current_price', models.CharField(max_length=25)),
                ('time_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_information', to='api.TimeData')),
            ],
        ),
    ]
