# Generated by Django 3.0.4 on 2020-04-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200322_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='time_information',
            field=models.ManyToManyField(to='api.TimeData'),
        ),
    ]
