# Generated by Django 3.0.4 on 2020-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200507_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='default_term',
            field=models.DurationField(blank=True, null=True, verbose_name='Prazo padrão'),
        ),
    ]
